### ISSUE TITLE
Servercrash on invalid Advanced setup

### ISSUE THREAD

**Issue by Firehunter23** [davboecki/SignCodePad#1]
When doing a wrong Third line in advanced placement the server crash.

2012-01-22 20:44:45 [SEVERE] Could not pass event PLAYER_INTERACT to SignCodePad
java.lang.NumberFormatException: For input string: "3,2-2,2"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1222)
    at java.lang.Double.parseDouble(Double.java:510)
    at de.davboecki.signcodepad.CodePadPlayerListener.handleCodeEnter(CodePadPlayerListener.java:576)
    at de.davboecki.signcodepad.CodePadPlayerListener.onPlayerInteract(CodePadPlayerListener.java:252)
    at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:335)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
    at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:266)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
    at net.minecraft.server.Packet15Place.a(SourceFile:39)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by davboecki** [comment]
Should be fixed through https://github.com/davboecki/SignCodePad/commit/e1339cd4fff8486497c54504be8446b613052b5c
